/**
 * Create Notion database with schema matching ScheduledTask DTO.
 *
 * Usage: npx tsx scripts/create-notion-database.ts
 *
 * Reads NOTION_TOKEN and NOTION_DATABASE_ID (parent page ID) from .env.
 * Outputs the new database ID so you can paste it back into .env.
 */

import { Client } from '@notionhq/client';
import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';

// ── Parse .env ──

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const envPath = path.resolve(__dirname, '..', '.env');
const envContent = fs.readFileSync(envPath, 'utf-8');
const env: Record<string, string> = {};
for (const line of envContent.split('\n')) {
  const trimmed = line.trim();
  if (!trimmed || trimmed.startsWith('#')) continue;
  const eqIdx = trimmed.indexOf('=');
  if (eqIdx === -1) continue;
  env[trimmed.slice(0, eqIdx).trim()] = trimmed.slice(eqIdx + 1).trim();
}

const NOTION_TOKEN = env['NOTION_TOKEN'];
const PARENT_PAGE_ID = env['NOTION_DATABASE_ID'];

if (!NOTION_TOKEN) {
  console.error('❌ NOTION_TOKEN not found in .env');
  process.exit(1);
}
if (!PARENT_PAGE_ID) {
  console.error('❌ NOTION_DATABASE_ID (parent page ID) not found in .env');
  process.exit(1);
}

// ── Notion client ──

const notion = new Client({ auth: NOTION_TOKEN });

// ── Database schema (mirrors createNotionPage property mapping) ──

const URGENCY_OPTIONS = [
  { name: '🔴 High', color: 'red' },
  { name: '🟡 Medium', color: 'yellow' },
  { name: '🟢 Low', color: 'green' },
] as const;

const STATUS_OPTIONS = [
  { name: '📋 Scheduled', color: 'blue' },
  { name: '🔄 In Progress', color: 'orange' },
  { name: '✅ Done', color: 'green' },
  { name: '❌ Cancelled', color: 'gray' },
] as const;

async function main() {
  console.log(`🔧 Creating Notion database on page ${PARENT_PAGE_ID}...\n`);

  const database = await notion.databases.create({
    parent: {
      type: 'page_id',
      page_id: PARENT_PAGE_ID,
    },
    title: [
      {
        type: 'text',
        text: { content: '🐟 Goofish Timetable' },
      },
    ],
    description: [
      {
        type: 'text',
        text: { content: 'Auto-generated by goofish-timetable-agent. Syncs Xianyu seller tasks.' },
      },
    ],
    properties: {
      // ── Title column ──
      'Task Name': {
        type: 'title',
        title: {},
      },

      // ── Buyer name ──
      Buyer: {
        type: 'rich_text',
        rich_text: {},
      },

      // ── Requirement description ──
      Requirement: {
        type: 'rich_text',
        rich_text: {},
      },

      // ── Urgency level (select) ──
      Urgency: {
        type: 'select',
        select: {
          options: URGENCY_OPTIONS,
        },
      },

      // ── Quoted price in CNY ──
      'Price (¥)': {
        type: 'number',
        number: {
          format: 'yuan',
        },
      },

      // ── Estimated work hours ──
      'Est. Hours': {
        type: 'number',
        number: {
          format: 'number',
        },
      },

      // ── Calendar date anchor ──
      Date: {
        type: 'date',
        date: {},
      },

      // ── Scheduled start datetime ──
      'Start Time': {
        type: 'date',
        date: {},
      },

      // ── Scheduled end datetime (includes buffer) ──
      'End Time': {
        type: 'date',
        date: {},
      },

      // ── Task status (select) ──
      Status: {
        type: 'select',
        select: {
          options: STATUS_OPTIONS,
        },
      },

      // ── Xianyu chat link ──
      'Chat Link': {
        type: 'url',
        url: {},
      },

      // ── Special notes / extra context ──
      Notes: {
        type: 'rich_text',
        rich_text: {},
      },
    },
  });

  const dbId = database.id;
  console.log(`✅ Database created successfully!`);
  console.log(`   Database ID: ${dbId}`);
  console.log(`   URL: https://notion.so/${dbId.replace(/-/g, '')}`);
  console.log('');
  console.log(`📝 Update your .env:`);
  console.log(`   NOTION_DATABASE_ID=${dbId}`);
}

main().catch((err) => {
  console.error('❌ Failed to create database:', err.message);
  if (err.body) {
    console.error('   Details:', JSON.stringify(err.body, null, 2));
  }
  process.exit(1);
});
